[package]
name = "images"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
skyfeed = { path = "../.." }
tokio = { version = "1.43.0", features = ["full", "time"] }
rusqlite = { version = "0.33.0", features = ["bundled"] }
chrono = "0.4.39"
regex = "1.11.1"
