[package]
name = "sqlite-feed"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.90.0"

[features]
local = []

[dependencies]
log = "0.4.25"
skyfeed = { git = "https://github.com/cyypherus/skyfeed.git", rev = "93899a464bc4c3a24a54c2e1e98ddd9ca0503662" }
# skyfeed = { path = "../.." }
tokio = { version = "1.43.0", features = ["full", "time"] }
rusqlite = { version = "0.33.0", features = ["bundled"] }
chrono = "0.4.39"
chrono-tz = "0.10"
regex = "1.11.1"
whatlang = "0.16.4"
metrics = "0.24.1"
metrics-exporter-prometheus = "0.16.2"
dotenv = "0.15.0"

[profile.release]
lto = true
